# Generated by Django 5.1.4 on 2025-02-08 20:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_subject_description_alter_subject_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
