# Generated by Django 5.1.4 on 2025-02-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_description_alter_subject_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
