# Generated by Django 5.1.4 on 2025-02-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_student_description_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
