# Generated by Django 5.1.4 on 2025-02-17 12:49

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_courselang'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek')], max_length=6)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField()),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.tutor')),
            ],
        ),
    ]
