# Generated by Django 5.1.4 on 2025-02-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_tutorlang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorlang',
            name='detail',
        ),
        migrations.AlterField(
            model_name='courselang',
            name='lang',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('uz', 'Uzbek')], max_length=6),
        ),
        migrations.AlterField(
            model_name='subjectlang',
            name='lang',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('uz', 'Uzbek')], max_length=6),
        ),
        migrations.AlterField(
            model_name='subjectlang',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tutorlang',
            name='lang',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('uz', 'Uzbek')], max_length=6),
        ),
    ]
