# Generated by Django 5.1.4 on 2025-02-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_remove_tutorlang_detail_alter_courselang_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselang',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek')], max_length=6),
        ),
        migrations.AlterField(
            model_name='subjectlang',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek')], max_length=6),
        ),
        migrations.AlterField(
            model_name='tutorlang',
            name='lang',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz', 'Uzbek')], max_length=6),
        ),
    ]
