# Generated by Django 5.1.4 on 2025-02-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_courselang_lang_alter_subjectlang_lang_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectlang',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='subjectlang',
            name='detail',
            field=models.CharField(max_length=255),
        ),
    ]
