# Generated by Django 5.1.4 on 2025-02-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_remove_subjectlang_keywords_alter_subjectlang_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectlang',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='tutorlang',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
