# Generated by Django 5.1.4 on 2025-02-18 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_subjectlang_image_tutorlang_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselang',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courselangs', to='course.course'),
        ),
    ]
