# Generated by Django 5.1.4 on 2025-02-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0016_alter_courselang_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="subjectlang",
            name="subject_tutor",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
