# Generated by Django 5.1.4 on 2025-02-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0017_subjectlang_subject_tutor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
