# Generated by Django 5.1.4 on 2025-02-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0018_alter_subject_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="image",
            field=models.ImageField(default=1, upload_to="images/"),
            preserve_default=False,
        ),
    ]
