# Generated by Django 5.1.4 on 2025-02-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_setting_aboutus_alter_setting_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
