# Generated by Django 5.1.4 on 2025-02-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_settinglang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settinglang',
            name='lang',
            field=models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('uz', 'Uzbek')], max_length=6),
        ),
    ]
